[project]
name = "Cyberdynamix"
version = "0.0.1"
description = "A WebAPP Bot Framework."
authors = [
    {name = "简律纯", email = "i@jyunko.cn"},
]
dependencies = [
    "flask>=2.3.3",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

